algo_name: PPO
ckpt: null
environment:
  env: Ray/Pong-v5
#  env: Ray/SpaceInvaders-v5
  is_atari: True
training:
  model:
    uses_new_env_runners: True
  lr: 1.0e-4
  gamma: 0.997
  train_batch_size: 256
  # Algo Specific
  num_sgd_iter: 10
  mini_batch_size_per_learner: 64
  lambda_: 0.95
  kl_coeff: 0.5
  clip_param: 0.1
  vf_clip_param: 10.0
stop:
#  env_runners/episode_return_mean: 20.0
  training_iteration: 200
  num_env_steps_sampled_lifetime: 5000000